<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="FB_RectangleChild" Id="{e621f85c-dffd-46a5-8c74-3e63e4e25c32}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_RectangleChild EXTENDS FB_Rectangle
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>