<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="FB_NormallyOpenSensor" Id="{62763c25-bf0a-4cc0-9276-55059e992b67}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_NormallyOpenSensor IMPLEMENTS I_Sensor
VAR
	Input AT %I* : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IsActive" Id="{55032022-ddfe-4e69-8bf0-bd902a6ee556}">
      <Declaration><![CDATA[PROPERTY IsActive : BOOL]]></Declaration>
      <Get Name="Get" Id="{f05c2218-f255-4b80-aa34-6ec6c6918596}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IsActive := Input;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <LineIds Name="FB_NormallyOpenSensor">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_NormallyOpenSensor.IsActive.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>