<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{de89c65d-ea9b-4ed7-951a-9b7852f9ad91}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	bCheckBox : BOOL;
	iComboBox : INT;
	sComboBox : STRING := 'Escolha uma cor';
	Cores : E_Cores;
	rSpinBox : REAL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>